language: haskell

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.

ghc:
  - 7.8.4
  - 7.6.3
  - 7.4.2

# We use the word 'test' in a broad sense (e.g. it includes the Agda
# test suite, the benchmark suite, the compilation with a specific set
# of dependencies, the testing of other programs like `hTags`, etc.) The
# tests are divided according to whether or not require the standard
# library.
#
# The current tests non-requiring the standard library are:
#
# make check-whitespace
# make succeed
# make fail
# make interaction
# make interactive
# make latex-test
# make examples
# make api-test
# make tests
# make TAGS (testing the hTags program)
# Compilation with GHC 7.8.4 using transformers 0.3.0.0 [Issue 1156]
#
# The current tests requiring the standard library are:
#
# make library-test
# make lib-succeed
# make compiler-test
# make benchmark-without-logs
env:
  - TEST=non_require_stdlib
  - TEST=require_stdlib

install:
  # Asking for the shell.
  - echo $SHELL

  # With old GHCs, we get an old cabal-install
  - cabal install cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH

  # Showing Cabal configuration
  - cat $HOME/.cabal/config

  # New Happy needed for haskell-src-exts
  - cabal install happy

  # New new Alex for us
  - cabal install alex

  # The Epic backend has been disabled. See Issue 1481.
  # Epic installation.
  # - sudo apt-get install libgc-dev
  # - cabal install epic

  # Required packages for running the LaTeX test-suite.
  #
  # Remark (19 April 2015). Travis (i.e. Ubuntu 12.04) uses an outdated
  # TeX Live 2009. The LaTeX test-suite requires the unicode-math package
  # which is not available in this version of TeX Live (see Issue 1022).

  # The LaTeX test-suite doesn't require the standard library.
  - case "$TEST" in
      "non_require_stdlib")
        sudo add-apt-repository ppa:texlive-backports/ppa -y &&
        sudo apt-get update &&
        sudo apt-get install texlive &&
        sudo apt-get install texlive-latex-extra &&
        sudo apt-get install texlive-xetex &&
        sudo apt-get install texlive-math-extra &&
        sudo apt-get install texlive-fonts-extra
        ;;

      "require_stdlib")
        ;;

      *)
        echo "Unrecognised TEST";
        exit 1
        ;;
    esac

  # Get the standard library.
  - case "$TEST" in
      "non_require_stdlib")
        ;;

      "require_stdlib")
       make up-to-date-std-lib
       ;;

      *)
        echo "Unrecognised TEST";
        exit 1
        ;;
    esac

  # The GHC version.
  - GHC_VERSION_TRAVIS=`ghc --numeric-version`

  # In Travis (because the Haskell platform is installed?) Cabal needs the
  # `--avoid-reinstalls` flag on GHC 7.4.2 and 7.6.3, else it will complain
  # about breaking previously installed packages [Issue 1520].

  # The `enable-test` option is required only if $TEST=require_stdlib.
  - case "$TEST" in
      "non_require_stdlib")
        if [ $GHC_VERSION_TRAVIS == 7.4.2 -o $GHC_VERSION_TRAVIS == 7.6.3 ]; then cabal install --avoid-reinstalls --only-dependencies -j; else cabal install --only-dependencies -j; fi
        ;;

      "require_stdlib")
        if [ $GHC_VERSION_TRAVIS == 7.4.2 -o $GHC_VERSION_TRAVIS == 7.6.3 ]; then cabal install --enable-tests --avoid-reinstalls --only-dependencies -j; else cabal install --enable-tests --only-dependencies -j; fi
       ;;

      *)
        echo "Unrecognised TEST";
        exit 1
        ;;
    esac

  # The `check-whitespace` test doesn't require the standard library.
  - case "$TEST" in
      "non_require_stdlib")
        make install-fix-agda-whitespace
        ;;

      "require_stdlib")
       ;;

      *)
        echo "Unrecognised TEST";
        exit 1
        ;;
    esac

  - export BUILD_DIR=$PWD/dist

  # The `enable-test` option is required only if $TEST=require_stdlib.
  - case "$TEST" in
      "non_require_stdlib")
        cabal configure -v2 --builddir=$BUILD_DIR
        ;;

      "require_stdlib")
        cabal configure -v2 --builddir=$BUILD_DIR --enable-tests
       ;;

      *)
        echo "Unrecognised TEST";
        exit 1
        ;;
    esac

  - cabal build -v2 --builddir=$BUILD_DIR

  # The `enable-test` option is required only if $TEST=require_stdlib.
  - case "$TEST" in
      "non_require_stdlib")
        cabal install -v2 --builddir=$BUILD_DIR
        ;;

      "require_stdlib")
        cabal install -v2 --builddir=$BUILD_DIR --enable-tests
       ;;

      *)
        echo "Unrecognised TEST";
        exit 1
        ;;
    esac

script:
  # Right now Haddock doesn't work, presumably because it consumes too
  # much memory.
  # - cabal haddock

  # TODO (07 May 2015): I couldn't add the following documentation inside the
  # case statement:
  # 1. Testing the hTags program.
  # 2. Testing compilation with transformers 0.3.0.0 which is shipped with
  # GHC 7.8.* [Issue 1156].

  - case "$TEST" in
      "non_require_stdlib")
        yes q | make BUILD_DIR=$BUILD_DIR check-whitespace succeed fail interaction interactive latex-test examples api-test tests &&

        make BUILD_DIR=$BUILD_DIR TAGS &&

        if [ $GHC_VERSION_TRAVIS == 7.8.4 ]; then cabal configure -v2 --builddir=$BUILD_DIR --constraint=transformers==0.3.0.0 && cabal -v2 --builddir=$BUILD_DIR build; fi
        ;;

      "require_stdlib")
        yes q | make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR library-test lib-succeed compiler-test benchmark-without-logs
        ;;

      *)
        echo "Unrecognised TEST";
        exit 1
        ;;
    esac

# Builds are loooong, we want to send an email as fast as possible.
matrix:
  fast_finish: true
  # allow_failures:
    # - ghc: A.B.C

# Every master and maintenance branches >= 2.4.3 or >= maint-2.4.2 must
# be here. You can also add your private branches if you want travis to
# test them.
branches:
  only:
    - master
    - maint-2.4.2
