language: haskell

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.

# Travis have no GHC 7.2.* installed because it is considered a technology
# preview (as per https://www.haskell.org/ghc/download_ghc_7_2_2). If
# necessary, we could use use the approach described in
# https://github.com/hvr/multi-ghc-travis.

ghc:
  - 7.8.4
  - 7.6.3
  - 7.4.2

install:
  # Apparently Travis doesn't have "time".
  - sudo apt-get install time

  # With old GHCs, we get an old cabal-install
  - cabal install cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH

  # Showing Cabal configuration
  - cat $HOME/.cabal/config

  # New Happy needed for haskell-src-exts
  - cabal install happy

  # New new Alex for us
  - cabal install alex

  # And Epic
  - sudo apt-get install libgc-dev
  - cabal install epic

  # Get the std-lib
  - make std-lib

  # cabal needs the --avoid-reinstalls flag on GHC 7.4.2, else it will complain about
  # breaking previously installed packages.
  - if [ `ghc --numeric-version` == 7.4.2 ]; then cabal install --enable-tests --avoid-reinstalls --only-dependencies -j; else cabal install --enable-tests --only-dependencies -j; fi

  - make install-fix-agda-whitespace
  - export BUILD_DIR=$PWD/dist
  - cabal configure -v2 --builddir=$BUILD_DIR --enable-tests
  - cabal build -v2 --builddir=$BUILD_DIR

  # "make install-bin" shouldn't take longer than 20-30 seconds, as it
  # reuses the build output from the above "cabal build". For this to
  # work, the exact same configure flags and build dir has to be used.
  # If the "make install-bin" runs longer than about a minute, it is
  # probably recompiling Agda and the Makefile or this file needs to
  # be fixed to make sure the same configure flags/build dir are
  # used everywhere.
  - make BUILD_DIR=$BUILD_DIR install-bin CABAL_OPTS=-v2

script:
  # Travis doesn't have LaTeX, not sure if we should include `latex-test`.
  - yes q | make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR check-whitespace succeed fail interaction interactive examples library-test lib-succeed compiler-test epic-test api-test tests benchmark exec-test

  # Right now Haddock doesn't work, presumably because it consumes too
  # much memory.
  # - cabal haddock

  # Testing hTags.
  - make BUILD_DIR=$BUILD_DIR TAGS

  # Testing compilation with transformers 0.3.0.0 which is shipped with
  # GHC 7.8.* (see Issue 1156).
  # (comment above at "make install-bin" about avoiding recompilation
  # also applies here!)
  - if [ `ghc --numeric-version` == 7.8.4 ]; then cabal configure -v2 --builddir=$BUILD_DIR --enable-tests --constraint=transformers==0.3.0.0 && cabal -v2 --builddir=$BUILD_DIR build; fi

# Builds are loooong, we want to send an email as fast as possible.
matrix:
  fast_finish: true
  # allow_failures:
    # - ghc: A.B.C

# Every master and maintenance branches >= 2.4.3 or >= maint-2.4.2 must
# be here. You can also add your private branches if you want travis to
# test them.
branches:
  only:
    - master
    - maint-2.4.2
