language: haskell

sudo: false

##############################################################################
# Installing the `kpsewhich` program

# The LaTeX/HTML test-suite requires:
# * `kpsewhich` (included in texlive-binaries)

# The `documentation` test requires:
# * `latex` (included in texlive-latex-base)
# * `utf8x.def` (included in texlive-latex-extra)
# * `dvipng` (included in dvipng)

# TODO (2016-03-06): We should install these packages only with the
# associated tests.

addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-binaries
    - texlive-latex-extra
    - dvipng

##############################################################################
# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.

ghc:
  - 7.8.4
  - 7.6.3

##############################################################################
# Tests

# We use the word 'test' in a broad sense (e.g. it includes the Agda
# test suite, the benchmark suite, the compilation with a specific set
# of dependencies, the testing of other programs like `hTags`, etc.) Almost
# all the tests are divided according to whether or not require the standard
# library.

# The current tests non-requiring the standard library are:
#
# make check-whitespace
# make succeed
# make fail
# make interaction
# make interactive
# make latex-html-test
# make examples
# make api-test
# make tests
# make TAGS (testing the hTags program)
# agda-mode compile (testing the Emacs mode)

# The current tests requiring the standard library are:
#
# make library-test
# make lib-succeed
# make lib-interaction
# make compiler-test
# make benchmark-without-logs

# Other tests: These tests use a some how different set up.
#
# ghc-7.8.4-transformers-0.3.0.0
# cpp
# haddock
# documentation

# Travis runs the builds on this order.
env:
  - TEST=non-require-stdlib
  - TEST=require-stdlib
  - TEST=ghc-7.8.4-transformers-0.3.0.0
  - TEST=cpp
  - TEST=haddock
  - TEST=documentation

##############################################################################
install:
  # How much memory we have.
  - vmstat -s

  # Asking for the shell.
  - echo $SHELL

  # The GHC version.
  - GHC_VERSION_TRAVIS=`ghc --numeric-version`

  # Higher GHC version available.
  - GHC_HIGHER_VERSION=7.8.4

  # Number of modules compile in parallel.
  - export JOBS=2

  # The Emacs version.
  - emacs --version

##############################################################################
# Installing the dependencies and latest versions of cabal-install,
# Alex and Happy

# N.B. that we run the tests `cpp` and `haddock` only with the higher
# GHC version available.

# N.B. that `cabal install` doesn't set up the number of jobs by default
# (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

# N.B. that we use the `--force-reinstalls` option [Issue 1520].

# TODO (2016-02-21): Split the long lines (`\` doesn't work).

  - if [[ ( $TEST = "non-require-stdlib" ) || ( $TEST = "require-stdlib" ) || (( $TEST = "cpp" || $TEST = "haddock" ) && $GHC_VERSION_TRAVIS = $GHC_HIGHER_VERSION ) ]]; then
       cabal install cabal-install &&
       export PATH=$HOME/.cabal/bin:$PATH &&
       cat $HOME/.cabal/config &&
       cabal install alex &&
       cabal install happy &&
       cabal install --enable-tests --only-dependencies --force-reinstalls;
    elif [[ $TEST = "ghc-7.8.4-transformers-0.3.0.0" && $GHC_VERSION_TRAVIS = 7.8.4 ]]; then
         cabal install cabal-install --constraint=transformers==0.3.0.0 &&
         export PATH=$HOME/.cabal/bin:$PATH &&
         cat $HOME/.cabal/config &&
         cabal install alex --constraint=transformers==0.3.0.0 &&
         cabal install happy --constraint=transformers==0.3.0.0 &&
         cabal install --enable-tests --only-dependencies --force-reinstalls --constraint=transformers==0.3.0.0;
    fi

##############################################################################
# Installing Agda

# We are installing Agda using
#
#  cabal configure <options>
#  cabal build
#  cabal copy
#  cabal register
#
# instead of
#
#  cabal install <options>
#
# due to the cabal-install issue https://github.com/haskell/cabal/issues/975.

# Note: `cabal build` sets up the number of jobs to $ncpus by default.
# (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

# We don't run `cabal install` because we are using `cabal configure` and
# `cabal build` (see Section 'cabal install ≠ Setup install' from
# http://www.vex.net/~trebla/haskell/cabal-cabal.xhtml).

  - export BUILD_DIR=$PWD/dist

  - if [[ $TEST = "non-require-stdlib" || $TEST = "require-stdlib" ]]; then
       cabal configure -v2 --builddir=$BUILD_DIR --enable-tests &&
       cabal build -v2 -j${JOBS} &&
       cabal copy &&
       cabal register;
    fi

##############################################################################
# Installing Epic

# The Epic backend has been removed. See Issue 1481.

  # - sudo apt-get install libgc-dev
  # - cabal install epic

##############################################################################
# Getting the standard library

  - if [ $TEST = "require-stdlib" ]; then
       make up-to-date-std-lib;
    fi

##############################################################################
# Installing fix-agda-whitespace

  - if [ $TEST = "non-require-stdlib" ]; then
       make install-fix-agda-whitespace;
    fi

##############################################################################
# Installing Sphinx

# TODO (2016-03-06): We are installing a concrete version of Sphinx
# because we don't know how to the install the latest no-beta version.

# Note that `pip install --user` put the binaries in
# `$HOME/.local/bin`.

  - if [ $TEST = "documentation" ]; then
       pip install --user -U Sphinx==1.3.6 &&
       export PATH=$HOME/.local/bin:$PATH;
    fi

##############################################################################
script:

##############################################################################

# We don't run LaTeX/XeLaTeX/LuaLaTeX on Travis (see Issues 1022 and
# 1675), but we still compare the generated tex/html files with the
# golden files.

  - if [ $TEST = "non-require-stdlib" ]; then
       make check-whitespace &&
       make AGDA_TESTS_OPTIONS="-j${JOBS}" BUILD_DIR=$BUILD_DIR succeed &&
       make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR fail &&
       make BUILD_DIR=$BUILD_DIR interaction &&
       make BUILD_DIR=$BUILD_DIR interactive &&
       make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR DONT_RUN_LATEX="Y" latex-html-test &&
       make BUILD_DIR=$BUILD_DIR examples &&
       make BUILD_DIR=$BUILD_DIR api-test &&
       make BUILD_DIR=$BUILD_DIR tests &&
       make BUILD_DIR=$BUILD_DIR TAGS &&
       echo "======================================================================" &&
       echo "==================== Testing the Emacs mode ==========================" &&
       echo "======================================================================" &&
       agda-mode compile;
    fi

##############################################################################

  - if [ $TEST = "require-stdlib" ]; then
       make BUILD_DIR=$BUILD_DIR library-test &&
       make BUILD_DIR=$BUILD_DIR lib-succeed &&
       make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR lib-interaction &&
       make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR compiler-test &&
       make BUILD_DIR=$BUILD_DIR benchmark-without-logs;
    fi

##############################################################################
# Testing compilation with transformers 0.3.0.0 which is shipped with
# GHC 7.8.* [Issues 1156 and 1539]

# N.B. that this test is not include in the Makefile tests.

  - if [[ $TEST = "ghc-7.8.4-transformers-0.3.0.0" && $GHC_VERSION_TRAVIS = 7.8.4 ]]; then
       cabal configure -v2 --builddir=$BUILD_DIR --enable-tests --constraint=transformers==0.3.0.0 &&
       cabal build -v2 -j${JOBS};
    fi

##############################################################################
# Testing compilation with cpp instead of cpphs [Issue 1647]

# N.B. that we run this test only with the higher GHC version available.

# N.B. that this test is not include in the Makefile tests.

  - if [[ $TEST = "cpp" && $GHC_VERSION_TRAVIS = $GHC_HIGHER_VERSION ]]; then
       cabal configure -v2 --enable-tests --builddir=$BUILD_DIR -f -cpphs &&
       cabal build -v2 -j${JOBS};
    fi

##############################################################################
# Testing Haddock [Issue 1773]

# N.B. that we run this test only with the higher GHC version available.

  - if [[ $TEST = "haddock" && $GHC_VERSION_TRAVIS = $GHC_HIGHER_VERSION ]]; then
       make BUILD_DIR=$BUILD_DIR haddock;
    fi

##############################################################################
# Testing documentation [Issue 1897]

# N.B. that we run this test only with the higher GHC version available.

  - if [[ $TEST = "documentation" && $GHC_VERSION_TRAVIS = $GHC_HIGHER_VERSION ]]; then
       make user-manual;
    fi

##############################################################################
matrix:
  exclude:
    - ghc: 7.6.3
      env: TEST=ghc-7.8.4-transformers-0.3.0.0
    - ghc: 7.6.3
      env: TEST=cpp
    - ghc: 7.6.3
      env: TEST=haddock
    - ghc: 7.6.3
      env: TEST=documentation

  # Builds are loooong, we want to send an email as fast as possible.
  fast_finish: true
  # allow_failures:
    # - ghc: A.B.C

##############################################################################
# Every master and maintenance branches >= 2.5 or >= maint-2.4 must
# be here. You can also add your private branches if you want travis to
# test them.

branches:
  only:
    - master
    - maint-2.4
