language: haskell

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.

ghc:
  - 7.8.4
  - 7.6.3
  # - 7.4.2

# We use the word 'test' in a broad sense (e.g. it includes the Agda
# test suite, the benchmark suite, the compilation with a specific set
# of dependencies, the testing of other programs like `hTags`, etc.) Almost
# all the tests are divided according to whether or not require the standard
# library.
#
# The current tests non-requiring the standard library are:
#
# make check-whitespace
# make succeed
# make fail
# make interaction
# make interactive
# make examples
# make api-test
# make tests
# make TAGS (testing the hTags program)
#
# The current tests requiring the standard library are:
#
# make library-test
# make lib-succeed
# make compiler-test
# make benchmark-without-logs
#
# N.B. that the ghc-7.8.4-transformers-0.3.0.0 test uses a different set up
# (see below).

# Travis runs the builds on this order.
env:
  - TEST=non-require-stdlib
  - TEST=require-stdlib
  - TEST=latex-test
  - TEST=ghc-7.8.4-transformers-0.3.0.0

install:
  # Asking for the shell.
  - echo $SHELL

  # The GHC version.
  - GHC_VERSION_TRAVIS=`ghc --numeric-version`

##############################################################################
# Installing latest versions of cabal-install, Alex and Happy

  - if [ $TEST = "latex-test" -o $TEST = "non-require-stdlib" -o $TEST = "require-stdlib" ]; then
       cabal install cabal-install &&
       export PATH=$HOME/.cabal/bin:$PATH &&
       cat $HOME/.cabal/config &&
       cabal install alex &&
       cabal install happy;
    fi

##############################################################################
# Installing dependencies

# In Travis (because the Haskell platform is installed?) Cabal needs the
# `--avoid-reinstalls` flag on GHC 7.4.2 and 7.6.3, else it will complain
# about breaking previously installed packages [Issue 1520].

# Note: `cabal install` doesn't set up the number of jobs by default
# (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

# The `enable-test` option is required only if $TEST=require-stdlib.

  - case $TEST in
      "latex-test" | "non-require-stdlib")
        if [ $GHC_VERSION_TRAVIS = 7.4.2 -o $GHC_VERSION_TRAVIS = 7.6.3 ]; then
           cabal install --avoid-reinstalls --only-dependencies;
        else
           cabal install --only-dependencies;
        fi
        ;;

      "require-stdlib")
        if [ $GHC_VERSION_TRAVIS = 7.4.2 -o $GHC_VERSION_TRAVIS = 7.6.3 ]; then
           cabal install --enable-tests --avoid-reinstalls --only-dependencies;
        else
           cabal install --enable-tests --only-dependencies;
        fi
        ;;
    esac

##############################################################################
# Installing Agda

# We are installing Agda using
#
#  cabal configure <options>
#  cabal build
#  cabal copy
#  cabal register
#
# instead of
#
#  cabal install <options>
#
# due to the cabal-install issue https://github.com/haskell/cabal/issues/975.

##############################################################################
# Running `cabal configure`

  - export BUILD_DIR=$PWD/dist

# The `enable-test` option is required only if $TEST=require-stdlib.

  - case $TEST in
      "latex-test" | "non-require-stdlib")
        cabal configure -v2 --builddir=$BUILD_DIR
        ;;

      "require-stdlib")
        cabal configure -v2 --builddir=$BUILD_DIR --enable-tests
        ;;
    esac

##############################################################################
# Running `cabal build`, `cabal copy` and `cabal register`

# Note: `cabal build` sets up the number of jobs to $ncpus by default.
# (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

# We don't run `cabal install` because we are using `cabal configure` and
# `cabal build` (see Section 'cabal install ≠ Setup install' from
# http://www.vex.net/~trebla/haskell/cabal-cabal.xhtml).

  - case $TEST in
      "latex-test" | "non-require-stdlib" | "require-stdlib")
        cabal build -v2 --builddir=$BUILD_DIR &&
        cabal copy &&
        cabal register
        ;;
    esac

##############################################################################
# Installing Epic

# The Epic backend has been removed. See Issue 1481.

  # - sudo apt-get install libgc-dev
  # - cabal install epic

##############################################################################
# Installing required packages for running the LaTeX test-suite
#
# Remark (19 April 2015). Travis (i.e. Ubuntu 12.04) uses an outdated
# TeX Live 2009. The LaTeX test-suite requires the unicode-math package
# which is not available in this version of TeX Live (see Issue 1022).

  - if [ $TEST = "latex-test" ]; then
       sudo add-apt-repository ppa:texlive-backports/ppa -y &&
       sudo apt-get update &&
       sudo apt-get install texlive &&
       sudo apt-get install texlive-latex-extra &&
       sudo apt-get install texlive-xetex &&
       sudo apt-get install texlive-math-extra &&
       sudo apt-get install texlive-fonts-extra;
    fi

##############################################################################
# Getting the standard library

  - if [ $TEST = "require-stdlib" ]; then
       make up-to-date-std-lib;
    fi

##############################################################################
# Testing compilation with transformers 0.3.0.0 which is shipped with
# GHC 7.8.* [Issue 1156]

  - if [ $TEST = "ghc-7.8.4-transformers-0.3.0.0" -a $GHC_VERSION_TRAVIS = 7.8.4 ]; then
       cabal install cabal-install --constraint=transformers==0.3.0.0 &&
       export PATH=$HOME/.cabal/bin:$PATH &&
       cat $HOME/.cabal/config &&
       cabal install alex --constraint=transformers==0.3.0.0 &&
       cabal install happy --constraint=transformers==0.3.0.0 &&
       cabal install --only-dependencies --constraint=transformers==0.3.0.0 &&
       cabal configure -v2 --builddir=$BUILD_DIR --constraint=transformers==0.3.0.0 &&
       cabal build -v2 --builddir=$BUILD_DIR;
    fi

##############################################################################
# Installing fix-agda-whitespace

  - if [ $TEST = "non-require-stdlib" ]; then
       make install-fix-agda-whitespace;
    fi

##############################################################################

script:
# Right now Haddock doesn't work, presumably because it consumes too
# much memory.
  # - cabal haddock

##############################################################################

  - if [ $TEST = "latex-test" ]; then
       make BUILD_DIR=$BUILD_DIR latex-test;
    fi

##############################################################################

  - if [ $TEST = "non-require-stdlib" ]; then
       make check-whitespace &&
       make BUILD_DIR=$BUILD_DIR succeed &&
       make BUILD_DIR=$BUILD_DIR fail &&
       make BUILD_DIR=$BUILD_DIR interaction &&
       make BUILD_DIR=$BUILD_DIR interactive &&
       make BUILD_DIR=$BUILD_DIR examples &&
       make BUILD_DIR=$BUILD_DIR api-test &&
       make BUILD_DIR=$BUILD_DIR tests &&
       make BUILD_DIR=$BUILD_DIR TAGS;
    fi

##############################################################################

  - if [ $TEST = "require-stdlib" ]; then
       make BUILD_DIR=$BUILD_DIR library-test &&
       make BUILD_DIR=$BUILD_DIR lib-succeed &&
       make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR compiler-test &&
       make BUILD_DIR=$BUILD_DIR benchmark-without-logs;
    fi

##############################################################################
matrix:
  exclude:
    - ghc: 7.6.3
      env: TEST=ghc-7.8.4-transformers-0.3.0.0
    - ghc: 7.4.2
      env: TEST=ghc-7.8.4-transformers-0.3.0.0

  # Builds are loooong, we want to send an email as fast as possible.
  fast_finish: true
  # allow_failures:
    # - ghc: A.B.C

##############################################################################
# Every master and maintenance branches >= 2.4.3 or >= maint-2.4.2 must
# be here. You can also add your private branches if you want travis to
# test them.

branches:
  only:
    - master
    - maint-2.4.2
