language: haskell

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.
ghc:
  - 7.8.3
  - 7.6.3
  - 7.4.2
  - 7.2.2
  - 7.0.4

install:
  # Apparently travis doesn't have "time".
  - sudo apt-get install time
  # With old GHCs, we get an old cabal-install
  - cabal install cabal-install
  # New happy needed for haskell-src-exts
  - cabal install happy
  # New new alex for us
  - cabal install alex
  # And cpphs
  - cabal install cpphs
  # And epic
  - sudo apt-get install libgc-dev
  - cabal install epic
  # Get the std-lib
  - make std-lib
  # GO GO GO
  - cabal install --only-dependencies -j
  - make install-fix-agda-whitespace

script:
  - cabal configure --disable-library-profiling -v2
  - cabal build -v2
  - cabal install -v2
  # Right now haddock doesn't work, presumably because it consumes too
  # much memory.
  # - cabal haddock
  - yes q | make check-whitespace succeed fail interaction examples library-test lib-succeed compiler-test epic-test api-test tests
  # Travis doesn't have latex, not sure if we should install it
  # - make latex-test

# Builds are loooong, we want to send an email as fast as possible.
matrix:
  fast_finish: true
